Fix RPC_Error at install
ValueError: Wrong @depends on '_compute_x_deviation_days' (compute method of field project.task.x_deviation_days). Dependency field 'planned_date_end' not found in model project.task.